package exception;

public enum ErrCode {

    ADDRESS_NOT_FOUND("ID DOESN'T EXIST"),
    STREET_NULL("STREET CANNOT BE NULL OR EMPTY"),
    CITY_NULL("CITY CANNOT BE NULL OR EMPTY"),
    POSTALCODE_NULL("POSTAL CODE CANNOT BE NULL OR EMPTY"),
    DATA_NOT_FOUND("THERE IS NO MATCHES FOUND FOR THE GIVEN TEXT"),

    PERSON_NOT_FOUND("ID DOESN'T EXIST"),
    FIRST_NAME_NULL("FIRST NAME CANNOT BE NULL OR EMPTY"),
    LAST_NAME_NULL("LAST NAME CANNOT BE NULL OR EMPTY"),
    EMAIL_NULL("EMAIL CANNOT BE NULL OR EMPTY"),
    BIRTH_DATE_NULL("BIRTH DATE CANNOT BE NULL OR EMPTY"),
    NAME_DUPLICATED("NAME ALREADY EXISTS"),
    EMAIL_DUPLICATED("EMAIL ALREADY EXISTS"),
    DATE_FORMAT_INVALID("ENTER BIRTH DATE IN DD-MM-YYYY FORMAT");

    private final String error;

    ErrCode (String error) {
        this.error = error;
    }

    public String getMessage() {
        return error;
    }
}
